### ISSUE TITLE
Error: Your application is conducting an HTTP request from outside of a zone!

### ISSUE THREAD

**Issue by mariohmol** [rangle/angular-ssr#61]
Hi there,

again great repo, thanks!!

My app is running and semms to be all working, but on log i can see this error (running in prod). 

Any ideas what that might be?

``` 
Your application is conducting an HTTP request from outside of a zone!
This will probably cause your application to render before the request finishes
Error
    at XMLHttpRequest.XmlHttpRequest._dispatchProgress (/home/myproject/v2/web/node_modules/angular-ssr/source/platform/http/xhr.ts:25:21)
    at XMLHttpRequest._onHttpResponseData (/home/myproject/v2/web/node_modules/xhr2/lib/xhr2.js:499:19)
    at IncomingMessage.<anonymous> (/home/myproject/v2/web/node_modules/xhr2/lib/xhr2.js:464:24)
    at ZoneDelegate.invokeTask (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:414:31)
    at Zone.runTask (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:181:47)
    at IncomingMessage.ZoneTask.invoke (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:476:38)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at ZoneDelegate.invokeTask (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:414:31)
    at Zone.runTask (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:181:47)
    at ZoneTask.invoke (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:476:38)
    at data.args.(anonymous function) (/home/myproject/v2/web/node_modules/zone.js/dist/zone-node.js:1392:25)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
``` 

Thanks

**Comment by e-schultz** [comment]
Do you have an example of where the `Http` module is being called in your code - trying to see what could be causing it to be called outside of a zone.

**Comment by mariohmol** [comment]
Based on my log.. is the normal / endpoint, where 99,9% of the times works. it's kind rare to see this error.. can you explain what `outside of a zone` means in that case?

**Comment by clbond** [comment]
@mariohmol OK what is happening here is that some code executing _outside of a zone_ is attempting to create an HTTP request. This is problematic because it means `angular-ssr` cannot wait for your HTTP request to finish before it renders the page. Therefore whatever is being retrieved is not yet going to have arrived when the final render happens.

This is most likely a bug in your code, not in `angular-ssr`. It is giving you that nice warning to tell you that something is wrong with your code. The render process will still succeed but the results probably won't be what you want.

Almost certainly, some of your code or some third-party code **other than Angular** is using `XMLHttpRequest`. You need to prevent it from doing so, or alter it so that it at least runs the XMLHttpRequest from inside a Zone context.

Closing. Post here if you need additional info. Post the code if you want us to tell you where the probem is.

**Comment by clbond** [comment]
In the past I have seen this issue with some translation libraries which attempt to retrieve their translation JSON and they are doing so with or `XMLHttpRequest` or a polyfilled `fetch()`which itself uses `XMLHttpRequest`.

To solve this issue, put a breakpoint in `XMLHttpRequest` constructor in `xhr2.js` and see what is constructing the request in the first place. Look at the call stack. Almost certainly, the call stack will have no Angular code in it. This is the problem. You need to find a way to make that code execute inside of a `Zone.run`.

**Comment by mariohmol** [comment]
Thanks for your answer! Not getting this issue anymore, good to know if i get this again will debug.

What i have now is all the requests doing based on Http from '@angular/http' (at least in the app itself)

I have some outside js scripts that are included in the html like, gmap, analytics , facebook and twitter da do requests as well... is thai considered in this warning as well?
