### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by SwamyKottur** [rangle/angular-ssr#81]
/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:1362
    return Error('Cannot resolve all parameters for \'' + stringify(typeOrFunc) + '\'(' +
           ^
Error: Cannot resolve all parameters for 'ServerPlatform'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ServerPlatform' is decorated with Injectable.
    at noAnnotationError (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:1362:12)
    at _dependenciesFor (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:2146:15)
    at resolveReflectiveFactory (/Users/jagger/Documents/work/destination-discovery/packages/core/src/di/reflective_provider.ts:116:1)
    at resolveReflectiveProvider (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:2050:82)
    at Array.map (<anonymous>)
    at resolveReflectiveProviders (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:2059:48)
    at Function.ReflectiveInjector.resolve (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:2287:16)
    at Function.ReflectiveInjector.resolveAndCreate (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:2319:79)
    at /Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:4297:51
    at /Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:4294:17
    at Object.createJitPlatform (/Users/jagger/Documents/work/destination-discovery/node_modules/@angular/core/bundles/core.umd.js:4294:17)
    at WebpackCompiler.createPlatform (/Users/jagger/Documents/work/destination-discovery/node_modules/angular-ssr/source/application/compiler/webpack/compiler.ts:22:12)
    at ApplicationBuilderFromSource.build (/Users/jagger/Documents/work/destination-discovery/node_modules/angular-ssr/source/application/builder/from-source.ts:22:31)
    at Object.<anonymous> (/Users/jagger/Documents/work/destination-discovery/node_modules/angular-ssr/source/bin/render.ts:36:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jagger/Documents/work/destination-discovery/node_modules/angular-ssr/bin/render.js:3:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jb-destination-discovery@0.1.0 build:prerender: `ng-render --module src/server.module --symbol ServerModule --preboot=preboot.json --inline=false --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jb-destination-discovery@0.1.0 build:prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jagger/.npm/_logs/2017-10-25T19_39_32_506Z-debug.log

**Comment by clbond** [comment]
Can you please point me to a repo where this is failing? The examples still work for me
