### ISSUE TITLE
Compatibility with Angular 5

### ISSUE THREAD

**Issue by DenisLaboureyras** [rangle/angular-ssr#85]
Hello,

Thanks for your awesome plugin, I've used it for 3 months now and it works like a charm.
I've tried today to upgrade my app to Angular 5, I managed to do it on my client config, but the server build is throwing me a lot of errors (see below).
Am I doing something wrong or do you plan on upgrading your module to Angular 5 ?

Kind regards,
Denis

ERROR in ./node_modules/angular-ssr/build/application/compiler/ngc/create.js
Module not found: Error: Can't resolve '@angular/compiler-cli/src/path_mapped_compiler_host' in '/home/data/app/node_modules/angular-ssr/build/application/compiler/ngc'
 @ ./node_modules/angular-ssr/build/application/compiler/ngc/create.js 4:34-96
 @ ./node_modules/angular-ssr/build/application/compiler/ngc/compiler.js
 @ ./node_modules/angular-ssr/build/application/compiler/factory.js
 @ ./node_modules/angular-ssr/build/application/compiler/index.js
 @ ./node_modules/angular-ssr/build/application/index.js
 @ ./node_modules/angular-ssr/build/index.js
 @ ./src/angular/main.server.ts
 @ ./src/angular/main.server-ssr.ts

ERROR in ./node_modules/angular-ssr/node_modules/@angular/cli/models/webpack-configs/production.js
Module not found: Error: Can't resolve '@angular/service-worker/build/webpack' in '/home/data/app/node_modules/angular-ssr/node_modules/@angular/cli/models/webpack-configs'
 @ ./node_modules/angular-ssr/node_modules/@angular/cli/models/webpack-configs/production.js 74:43-91
 @ ./node_modules/angular-ssr/node_modules/@angular/cli/models/webpack-configs/index.js
 @ ./node_modules/angular-ssr/node_modules/@angular/cli/models/webpack-config.js
 @ ./node_modules/angular-ssr/build/application/compiler/webpack/config/cli.js
 @ ./node_modules/angular-ssr/build/application/compiler/webpack/config/index.js
 @ ./node_modules/angular-ssr/build/application/compiler/factory.js
 @ ./node_modules/angular-ssr/build/application/compiler/index.js
 @ ./node_modules/angular-ssr/build/application/index.js
 @ ./node_modules/angular-ssr/build/index.js
 @ ./src/angular/main.server.ts
 @ ./src/angular/main.server-ssr.ts

ERROR in [at-loader] ./node_modules/angular-ssr/build/application/compiler/ngc/resource-resolver.d.ts:1:10 
    TS2305: Module '"/home/data/app/node_modules/@angular/compiler-cli/index"' has no exported member 'ModuleResolutionHostAdapter'.

ERROR in [at-loader] ./node_modules/angular-ssr/build/platform/document/tokens.d.ts:1:10 
    TS2305: Module '"/home/data/app/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

ERROR in [at-loader] ./node_modules/angular-ssr/build/platform/module/tokens.d.ts:1:10 
    TS2305: Module '"/home/data/app/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

ERROR in [at-loader] ./node_modules/angular-ssr/build/platform/platform.d.ts:2:22 
    TS2420: Class 'ServerPlatform' incorrectly implements interface 'PlatformRef'.
  Property '_injector' is missing in type 'ServerPlatform'.

**Comment by lpmusicon** [comment]
Hey,
I'm getting different error on ng5 using static rendering:
`/mnt/c/Users/user/Documents/GitHub-Projects/myproject/node_modules/angular-ssr/build/platform/document/tokens.js:3
exports.TemplateDocument = new core_1.OpaqueToken('TemplateDocument');
                           ^

TypeError: core_1.OpaqueToken is not a constructor
    at Object.<anonymous> (/mnt/c/Users/user/Documents/GitHub-Projects/myproject/node_modules/angular-ssr/build/platform/document/tokens.js:3:28)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/user/Documents/GitHub-Projects/myproject/node_modules/angular-ssr/build/platform/document/container.js:3:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)`

After some reading, I think this is due to deprecation of OpaqueToken in Angular5

**Comment by anvial** [comment]
I've the same problem, is there any solution of this issue?

**Comment by lpmusicon** [comment]
@anvial If your app really depends on this SSR package I'd consider staying on ng4. However, if you can use dynamic prerendering in node you should definitely check out angular/universal package

**Comment by seanmavley** [comment]
@DenisLaboureyras Great. You have any write-up about your steps?

**Comment by lpmusicon** [comment]
@seanmavley Are You looking for static or dynamic prerendering?

**Comment by monoflash** [comment]
There, in plain Russian, it's written: "The official example on the english language: https://github.com/angular/universal-starter"

Who does not know Russian, welcome: https://github.com/angular/universal-starter
